name: CI

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: View context attributes # scripts
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - uses: actions/github-script@v6 # Env as input
        env:
          FIRST_NAME: Chris
          LAST_NAME: Young
        with:
          script: |
            const { FIRST_NAME, LAST_NAME } = process.env
            
            console.log(`Hello ${FIRST_NAME} ${LAST_NAME}`)

      - name: Adding markdown # Summary
        run: echo '### Hello DevUp! :rocket:' >> $GITHUB_STEP_SUMMARY
      - uses: actions/github-script@v6 # Env as input
        with:
          script: |
                core.summary
                  .addHeading('Test Results')
                  .addCodeBlock(fs.readFile('jest.config.js'), "js")
                  .addTable([
                    [{data: 'File', header: true}, {data: 'Result', header: true}],
                    ['foo.js', 'Pass '],
                    ['bar.js', 'Fail '],
                    ['test.js', 'Pass ']
                  ])
                  .addLink('View test results!', 'https://github.com')
                  .write()

      - name: Testing Summary # Complex Summary
        uses: actions/github-script@v6
        with:
          script: |
              console.log('foo')
              core.summary
              .addHeading('Test Results')
#              .addCodeBlock(generateTestResults(), "js")
#              .addTable([
#              [{data: 'File', header: true}, {data: 'Result', header: true}],
#              ['foo.js', 'Pass '],
#              ['bar.js', 'Fail '],
#              ['test.js', 'Pass ']
#            ])
#              .addLink('View test results!', 'https://github.com')
#              .write()
