name: PR Close

on:
  pull_request:
    branches:
      - main
    types: [ closed ]

jobs:
  build:
    if: |
      github.event.pull_request.merged == true
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: View context attributes # scripts
        uses: actions/github-script@v6
        with:
          script: console.log(context)
      - uses: actions/github-script@v6 # Env as input
        env:
          FIRST_NAME: Chris
          LAST_NAME: Young
        with:
          script: |
            const { FIRST_NAME, LAST_NAME } = process.env
            
            console.log(`Hello ${FIRST_NAME} ${LAST_NAME}`)

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: |
            build.json
            package.json

  next-job-to-run:
    runs-on: 'ubuntu-latest'
    needs: 'build'
    strategy:
      matrix:
        file: ['build.json', 'package.json']
    steps:
      - name: Download a Build Artifact
        uses: actions/download-artifact@v3

      - uses: actions/github-script@v6 # Env as input
        env:
          FILE_PATH: ${{ matrix.file }}
        with:
          script: |
            const { FILE_PATH } = process.env
            const { promises: fs } = require('fs')
            const path = './dist/' + FILE_PATH
            core.summary
              .addHeading('Test Results')
              .addCodeBlock(await fs.readFile(path, 'utf8'), "ts")
              .addTable([
                [{data: 'File', header: true}, {data: 'Result', header: true}],
                ['foo.js', 'Pass '],
                ['bar.js', 'Fail '],
                ['test.js', 'Pass ']
              ])
              .addLink('View test results!', 'https://github.com')
              .write()

