name: Hub Publish (Prod)

on:
  release:
    types:
      - released

permissions:
  id-token: write
  contents: read

jobs:
  publish:
    runs-on: 'self-hosted'
    strategy:
      matrix:
        image_name: ['hub/api', 'hub/ui']
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'yarn'

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.13
        with:
          versionSpec: '5.x'

      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.13
        with:
          useConfigFile: true

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Nexus
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}
          registry: https://nexus.swimlane.io:5000

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::221643344216:role/prod-shared-resources-global-github-ecr-push
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: ReTag
        uses: EuphoricSystems/docker-promote-image@1.0.0
        if: ${{ steps.gitversion.outputs.preReleaseLabel == '' }}
        with:
          src: nexus.swimlane.io:5000/${{ matrix.image_name }}:${{steps.gitversion.outputs.shortSha}}
          destinations: |
            nexus.swimlane.io:5000/${{ matrix.image_name }}:${{steps.gitversion.outputs.semVer}}
            nexus.swimlane.io:5000/${{ matrix.image_name }}:latest
            ${{ steps.login-ecr.outputs.registry }}/${{ matrix.image_name }}:${{steps.gitversion.outputs.semVer}}
